name: "Предложение нового контента"
description: "Добавить статью/материал в лор"
title: "[Новый контент] Краткое описание"
labels: ["Новый контент"]
body:
  - type: dropdown
    id: proposal_category
    attributes:
      label: "Категория"
      options:
        - "Вооружение"
        - "Вселенная"
        - "Государства"
        - "Истории"
        - "Корпорации"
        - "Объекты"
        - "Организации"
        - "Повседневность"
        - "Расы"
        - "Существа"
        - "Технологии"
        - "Товары"
        - "Явления"
        - "Другое"
    validations:
      required: true

  - type: markdown
    id: proposal_info
    attributes:
      value: |
        <details>
          <summary> ℹ️ Автоматический лейбл. Не удаляйте этот блок. </summary>
          Этот блок добавляет лейбл на основе выбранной категории.
        </details>

  - type: input
    id: proposal_label_hidden
    attributes:
      label: "Служебное поле (не изменять)"
      value: ${{ github.event.issue.labels[1].name }}
    validations:
      required: false

  - type: textarea
    id: new_content
    attributes:
      label: "Описание"
      description: "Подробно опишите, что вы хотите добавить (персонаж, объект, событие и т.д.)"
    validations:
      required: true
