name: "Ошибка"
description: "Сообщить о неточности или проблеме"
title: "[Ошибка] Краткое описание"
labels: ["Ошибка"]
body:
  - type: dropdown
    id: category
    attributes:
      label: "Категория"
      options:
        - "Вооружение"
        - "Вселенная"
        - "Государства"
        - "Истории"
        - "Корпорации"
        - "Объекты"
        - "Организации"
        - "Повседневность"
        - "Расы"
        - "Существа"
        - "Технологии"
        - "Товары"
        - "Явления"
        - "Другое"
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: "Описание ошибки"
      placeholder: "Пример: В статье о корпорации «Нанотрейзен» ошибка в разделе о флоте"
    validations:
      required: true
