name: "Ошибка"
description: "Сообщить о неточности или проблеме"
title: "[Ошибка] Краткое описание"
labels: ["Ошибка"]
body:
  - type: dropdown
    id: category
    attributes:
      label: "Категория"
      options:
        - "Вооружение"
        - "Вселенная"
        - "Государства"
        - "Истории"
        - "Корпорации"
        - "Объекты"
        - "Организации"
        - "Повседневность"
        - "Расы"
        - "Существа"
        - "Технологии"
        - "Товары"
        - "Явления"
        - "Другое"
    validations:
      required: true
  - type: markdown
    id: category_label
    attributes:
        label: "Скрытый лейбл ошибки"
        value: |
          <details>
            <summary> ℹ️ Автоматический лейбл. Не удаляйте этот блок. </summary>
            Этот блок добавляет автоматический лейбл на основе выбранной категории.
            <br>
          </details>
    
  - type: input
    id: category_label_hidden
    validations:
      required: false
    attributes:
        label: "Скрытый input для лейбла категории"
        value: ${{ github.event.issue.labels[1].name }}
        
  - type: textarea
    id: issue
    attributes:
      label: "Описание ошибки"
      placeholder: "Пример: В статье о корпорации «Нанотрейзен» ошибка в разделе о флоте"
    validations:
      required: true
