name: "Вопрос по текущей статье"
description: "Задать вопрос или запросить уточнение по существующей статье."
title: "[Вопрос] Краткое описание вопроса"
labels: ["Вопрос", "Текущая статья"]
body:
  - type: input
    id: article_name
    attributes:
      label: "Название статьи"
      description: "Укажите название статьи, по которой возник вопрос."
      placeholder: "Пример: Описание расы Слаймолюды"
    validations:
      required: true

  - type: textarea
    id: question_text
    attributes:
      label: "Текст вопроса"
      description: "Подробно опишите ваш вопрос или запрос на уточнение."
      placeholder: "Пример: В разделе 'Биология' не совсем понятно, как происходит размножение. Можно уточнить этот момент?"
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: "Категория"
      options:
        - "Вооружение"
        - "Вселенная"
        - "Государства"
        - "Истории"
        - "Корпорации"
        - "Объекты"
        - "Организации"
        - "Повседневность"
        - "Расы"
        - "Существа"
        - "Технологии"
        - "Товары"
        - "Явления"
        - "Другое"
    validations:
      required: true
  - type: markdown
    id: category_label
    attributes:
        value: |
          <details>
            <summary> ℹ️ Автоматический лейбл. Не удаляйте этот блок. </summary>
            Этот блок добавляет автоматический лейбл на основе выбранной категории.
            <br>
          </details>
    
  - type: input
    id: category_label_hidden
    validations:
      required: false
    attributes:
        value: ${{ github.event.issue.labels[1].name }}
